### ISSUE TITLE
Rename this repo and (blog-official)

### ISSUE THREAD

**Issue by goodhoko** [tonarino/blog-template#8]
The repo that actually hosts our blog is https://github.com/tonarino/blog-official while this repo is a template for any Notion-backed blog.

We'd like to
- [x] rename `blog-official` to just `blog`
- [x] rename this repo to `blog-template` or similiar, subject to bikeshedding
- [x] rename the default branch in the new `blog` repo to `main` (from the unintuitive `official`)

**Comment by skywhale** [comment]
@bschwind @goodhoko `blog-official` is renamed to `blog`.
